RUN mvn clean install -DskipTests

# Etapa 1: Builder com Maven e Java 21
FROM maven:3.9-eclipse-temurin-21 as builder

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o pom.xml e baixar dependências antes do código (cache eficiente)
COPY pom.xml ./
RUN mvn dependency:go-offline -B

# Copiar o restante do código
COPY src ./src

# Construir o projeto
RUN mvn clean package -DskipTests

# Etapa 2: Executar o JAR com uma imagem menor
FROM eclipse-temurin:21-jre

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o JAR gerado para a imagem final
COPY --from=builder /app/target/*.jar app.jar

# Definir o comando de execução
ENTRYPOINT ["java", "-jar", "app.jar"]
